### ISSUE TITLE
gtk-examples/goroutines: too many closure args: have 2, max allowed 1

### ISSUE THREAD

**Issue by pebbe** [gotk3/gotk3-examples#8]
The top label in the example `goroutines` is not updated, and every time the example tries to do so, it prints this message on the console:
```
too many closure args: have 2, max allowed 1
```

**Comment by Bios-Marcel** [comment]
This seems to be an issue within `glib.goMarshal`. It works fine with functions that have either zero or one parameters, however, everything bigger than that doesn't seem to work. I think this should be addressed, however it can probably always be worked around very easily. In the case of the example, this would be a possible workaround:

```Go
_, err := glib.IdleAdd(func() {
    LabelSetTextIdle(topLabel, s)
})
```
